version: "3.9"

services:
  public_service:
    build: ..
    working_dir: /PublicService/app
    ports:
      - "8090:8090"
      - "5005:5005"
    command: mvn clean spring-boot:run
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: challenge
    ports:
      - 5432:5432