version: "3.9"

services:
  public_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: public_service
    working_dir: /SubscriptionService/app
    ports:
      - "8090:8090"
      - "5005:5005"
    command: mvn clean spring-boot:run
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: challenge
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3.9-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "secretcookie"
    ports:
      - "5672:5672"
      - "15672:15672"