version: "3.9"

services:
  eurekaserver:
    container_name: eurekaserver
    build:
      context: ./EurekaServer
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    image: eurekaserver
    command: mvn clean spring-boot:run
    networks:
      - private-network
  gateway_service:
    container_name: gateway_service
    build:
      context: ./CloudGateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    image: gateway_service
    command: mvn clean spring-boot:run
    networks:
      - private-network
  subscriptionservice:
    container_name: subscriptionservice
    build:
      context: ./SubscriptionService
      dockerfile: Dockerfile
    image: subscription_service
    command: mvn clean spring-boot:run
    networks:
      - private-network
  emailservice:
    container_name: emailservice
    build:
      context: ./EmailService
      dockerfile: Dockerfile
    image: email_service
    command: mvn clean spring-boot:run
    networks:
      - private-network
  db:
    container_name: postgresservice
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: challenge
    networks:
      - private-network
  rabbitmq:
    container_name: Dockerfile
    image: rabbitmq:3.9-management
    networks:
      - private-network
networks:
  private-network:
    name: private-network
    driver: bridge


