spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/challenge
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5432/challenge
    user: postgres
    password: password
    baseline-description: true
server:
  port:8090