spring:
  application:
    name: EurekaServer
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    secure-port: 443
    secure-port-enabled: true
    non-secure-port: 80
    non-secure-port-enabled: false
    hostname: eurekaserver
    namespace: eurekaserver
