spring:
  application:
    name: EmailService
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
mq:
  queue:
    send-email: send-email