spring:
  application:
    name: EmailService
  rabbitmq:
    host: rabbitmq
    port: 5672
    stream:
      username: guest
      password: guest
  mail:
    host: smtp.gmail.com
    username: damouracunha@gmail.com
    password: suyngkwlliqcuslx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    hostname: emailservice
mq:
  queue:
    send-email: send-email
email:
  production:
    active: true
  test: damouracunha@gmail.com