spring:
  main:
    web-application-type: reactive
  application:
    name: CloudGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaserver:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: gateway_service
