spring:
  application:
    name: subscriptionservice
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://postgresservice:5432/challenge
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://postgresservice:5432/challenge
    user: postgres
    password: password
    baseline-description: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    stream:
      username: guest
      password: guest
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: subscriptionservice
mq:
  queue:
    send-email: send-email